<?php
/**
 * @var array|Module\Core\Models\Menu $menuElements
 */

use Module\Core\Models\Content;

$level = 1;

echo '<ul class="nav navbar-nav navbar-right">';
$isActive = false;
$uri = trim($this->router->getRewriteUri(), "/ ");
foreach ($menuElements as $k => $elements) {
    if (!$this->acl->checkViewLevel($elements->viewLevel->getRolesArray()) || $elements->getStatus() != Content::STATUS_PUBLISHED) continue;

    $active = "";
    if ($elements->getPath() != "#" && substr($elements->getPath(), 0, 4) != "http") {
        $path = $this->url->get($elements->getPath());
        if (!$isActive && $uri == trim($elements->getPath(), "/ ")) {
            $active = "active";
            $isActive = true;
        }
    } else {
        $path = $elements->getPath();
    }

    if ($elements->getLevel() <= $level) {
        if ($elements->getLevel() < $level) {
            echo "</li>";
            for ($i = $level - $elements->getLevel(); $i; $i--) {
                echo "</ul></li>";
            }
        }
        if (isset($menuElements[$k+1]) && $menuElements[$k+1]->getParentId() == $elements->getId()) {
            if ($elements->getLevel() == 1) {
                echo "<li class=\"dropdown $active\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href='$path'>";
                if (!empty($elements->getPrepend())) {
                    echo "<i class=\"$elements->prepend\"></i> ";
                }
                if ($elements->getShowTitle()) {
                    echo $elements->title;
                }
                echo "</a><ul class=\"dropdown-menu\">";
            } else {
                echo "<li class=' dropdown-submenu$active'><a href=\"$path\">";
                if (!empty($elements->getPrepend())) {
                    echo "<i class=\"$elements->prepend\"></i> ";
                }
                if ($elements->getShowTitle()) {
                    echo $elements->title;
                }
                echo "</a><ul class=\"dropdown-menu\">";
            }

        } else {
            echo "<li class=\"$active\"><a href='$path' title='$elements->title'>";
            if (!empty($elements->getPrepend())) {
                echo "<i class=\"$elements->prepend\"></i> ";
            }
            if ($elements->getShowTitle()) {
                echo $elements->title;
            }
            echo "</a>";
        }
    } elseif ($elements->level > $level) {
        if (isset($menuElements[$k+1]) && $menuElements[$k+1]->getParentId() == $elements->getId()) {
            echo "<li class='dropdown-submenu $active'><a href=\"$path\">";
            if (!empty($elements->getPrepend())) {
                echo "<i class=\"$elements->prepend\"></i> ";
            }
            if ($elements->getShowTitle()) {
                echo $elements->title;
            }
            echo "</a><ul class=\"dropdown-menu\">";
        } else {
            echo "<li class=\"$active\"><a href='$path'>";
            if (!empty($elements->getPrepend())) {
                echo "<i class=\"$elements->prepend\"></i> ";
            }
            if ($elements->getShowTitle()) {
                echo $elements->title;
            }
            echo "</a>";
        }
    }

    $level = $elements->level;
}
echo '</ul>';