<?php
/**
 * @var stdClass $debugWidget
 */
?>
<div id='pdw-panel-request' class='pdw-panel request'>
	<div class='title'>
		<h2>Request Info <a class='pdw-panel-close'>&times;</a></h2>
	</div>
	<div class='panel-content'>
        <h3 class='collapser'>Current route</h3>
        <table class='pdw-data-table table-striped'>
            <thead>
            <tr>
                <th>Key</th>
                <th>Value</th>
            </tr>
            </thead>
            <tbody>
            <?php

            if(isset($debugWidget->router)){
                $router = array(
                    '_pattern' => $debugWidget->router->getPattern(),
                    '_compiledPattern' => $debugWidget->router->getCompiledPattern(),
                    '_paths' => $debugWidget->router->getPaths(),
                    '_hostname' => $debugWidget->router->getHostname(),
                    '_converters' => $debugWidget->router->getConverters(),
                    '_name' => $debugWidget->router->getName(),
                    '_beforeMatch' => $debugWidget->router->getBeforeMatch(),
                    '_group' => $debugWidget->router->getGroup(),
                );
                foreach($router as $k=>$v):
                    echo "<tr>";
                    echo "<td>{$k}</td>";
                    echo "<td><pre><code>";
                    print_r($v);
                    echo "</code></pre></td>";
                    echo "</tr>";
                endforeach;
            }
            ?>
            </tbody>
        </table>
		<h3 class='collapser'>$_SESSION</h3>
		<table class='pdw-data-table table-striped'>
			<thead>
				<tr>
					<th>Key</th>
					<th>Value</th>
				</tr>
			</thead>
			<tbody>
			<?php

            if(isset($_SESSION)){
				foreach($_SESSION as $k=>$v):
					echo "<tr>";
						echo "<td>{$k}</td>";
						echo "<td><pre><code >";
							print_r($v);
						echo "</code></pre></td>";
					echo "</tr>";
				endforeach;
            }
			?>
			</tbody>
		</table>

		<h3 class='collapser'>$_COOKIE</h3>
		<table class='pdw-data-table'>
			<thead>
				<tr>
					<th>Key</th>
					<th>Value</th>
				</tr>
			</thead>
			<tbody>
			<?php
				foreach($_COOKIE as $k=>$v):
					echo "<tr>";
						echo "<td>{$k}</td>";
						echo "<td><pre><code>";
							print_r($v);
						echo "</code></pre></td>";
					echo "</tr>";
				endforeach;
			?>
			</tbody>
		</table>

		<h3 class='collapser'>$_GET</h3>
		<table class='pdw-data-table'>
			<thead>
				<tr>
					<th>Key</th>
					<th>Value</th>
				</tr>
			</thead>
			<tbody>
			<?php
				foreach($_GET as $k=>$v):
					echo "<tr>";
						echo "<td>{$k}</td>";
						echo "<td><pre><code>";
							print_r($v);
						echo "</code></pre></td>";
					echo "</tr>";
				endforeach;
			?>
			</tbody>
		</table>

		<h3 class='collapser'>$_POST</h3>
		<table class='pdw-data-table'>
			<thead>
				<tr>
					<th>Key</th>
					<th>Value</th>
				</tr>
			</thead>
			<tbody>
			<?php
				foreach($_POST as $k=>$v):
					echo "<tr>";
						echo "<td>{$k}</td>";
						echo "<td><pre><code>";
							print_r($v);
						echo "</code></pre></td>";
					echo "</tr>";
				endforeach;
			?>
			</tbody>
		</table>

		<h3 class='collapser'>$_FILES</h3>
		<table class='pdw-data-table'>
			<thead>
				<tr>
					<th>Key</th>
					<th>Value</th>
				</tr>
			</thead>
			<tbody>
			<?php
				foreach($_FILES as $k=>$v):
					echo "<tr>";
						echo "<td>{$k}</td>";
						echo "<td><pre><code>";
							print_r($v);
						echo "</code></pre></td>";
					echo "</tr>";
				endforeach;
			?>
			</tbody>
		</table>

	</div>
</div>
