<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("user/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("user/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Auth Of Key</th>
            <th>Hash Of Key</th>
            <th>Password</th>
            <th>Reset Of Token</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
            <th>Register Of Date</th>
            <th>Last Of Visit Of Date</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $user) { ?>
        <tr>
            <td><?php echo $user->getId() ?></td>
            <td><?php echo $user->getUsername() ?></td>
            <td><?php echo $user->getAuthKey() ?></td>
            <td><?php echo $user->getHashKey() ?></td>
            <td><?php echo $user->getPassword() ?></td>
            <td><?php echo $user->getResetToken() ?></td>
            <td><?php echo $user->getEmail() ?></td>
            <td><?php echo $user->getRole() ?></td>
            <td><?php echo $user->getStatus() ?></td>
            <td><?php echo $user->getRegisterDate() ?></td>
            <td><?php echo $user->getLastVisitDate() ?></td>
            <td><?php echo $this->tag->linkTo(array("user/edit/" . $user->getId(), "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("user/delete/" . $user->getId(), "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("user/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("user/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("user/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("user/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
