<?php
/**
 * @copyright   2006 - 2015 Magnxpyr Network
 * @license     New BSD License; see LICENSE
 * @link        http://www.magnxpyr.com
 * @author      Stefan Chiriac <stefan@magnxpyr.com>
 * @var \Phalcon\Mvc\View\Engine $this
 * @var \Core\Forms\LoginForm $form
 * @var int $status
 */

echo $this->getContent();
echo $this->tag->form(['user/confirm-email']); ?>
    <fieldset>
        <div class="form-group form-max-size">
            <div class="input-group">
                <span class="input-group-addon" id="email-addon">@</span>
                <?php echo $form->render('email', ['class' => 'form-control', 'aria-describedby' => "email-addon"]); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->render('Send'); ?>
        </div>
    </fieldset>
</form>
