<?php
/**
 * @copyright   2006 - 2015 Magnxpyr Network
 * @license     New BSD License; see LICENSE
 * @link        http://www.magnxpyr.com
 * @author      Stefan Chiriac <stefan@magnxpyr.com>
 * @var \Core\Forms\LoginForm $form
 * @var \Phalcon\Mvc\View\Engine $this
 */
echo $this->getContent();
?>
<div class="login-page">
    <div class="login-box">
        <div class="login-box-body">
            <p class="login-box-msg">Sign in to start your session</p>
            <?php echo $this->tag->form(array('user/login')); ?>
            <fieldset>
                <div class="form-group">
                    <?php echo $form->label('username', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="username-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <?php echo $form->render('username', array('class' => 'form-control', 'aria-describedby' => "username-addon")); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo $form->label('password', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="password-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <?php echo $form->render('password', array('class' => 'form-control', 'aria-describedby' => "password-addon")); ?>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-8">
                        <?php echo $form->render('remember') . ' ' . $form->label('remember'); ?>
                    </div>
                    <div class="col-xs-4">
                        <?php echo $form->render('Login'); ?>
                    </div>
                </div>


                        <!--social media links-->


                    <div class="social-auth-links text-center">
                        <p> or </p>
                        <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
                        <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
                    </div>


                <div class="form-group">
                    <div class="input-group">
                        <?php echo $this->tag->linkTo(array('user/register', 'Sign Up', 'class' => 'btn btn-success')); ?>
                    </div>
                </div>


            </fieldset>
            <?php echo $form->render('csrf', ['value' => $this->security->getToken()]); ?>
            <?php echo $this->tag->endForm(); ?>
        </div>
    </div>
</div>


       <!-- <div class="page-header">
                <h2>Don't have an account yet?</h2>
            </div>
            <p>Create an account to take full advantage of our website.</p>  -->



