<?php
/**
 * @copyright   2006 - 2015 Magnxpyr Network
 * @license     New BSD License; see LICENSE
 * @link        http://www.magnxpyr.com
 * @author      Stefan Chiriac <stefan@magnxpyr.com>
 * @var \Core\Forms\LoginForm $form
 * @var \Phalcon\Mvc\View\Engine $this
 */

echo $this->getContent();
?>
<div class="row">
    <div class="col-md-9 col-sm-8">
        <div class="col-lg-8 col-md-10">
            <?php echo $this->tag->form(array('user/login')); ?>
            <?php echo $this->tag->hiddenField(array(
                'id' => 'token',
                'name' => $this->security->getTokenKey(),
                'value' => $this->security->getToken()
            )); ?>

            <fieldset>
                <div class="form-group">
                    <?php echo $form->label('username', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="username-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <?php echo $form->render('username', array('class' => 'form-control', 'aria-describedby' => "username-addon")); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo $form->label('password', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="password-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <?php echo $form->render('password', array('class' => 'form-control', 'aria-describedby' => "password-addon")); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php /**
                     * @TODO Forgot password
                     * @TODO Remember me
                     * */ ?>
                    <p class="help-block"></p>
                    <?php echo $this->tag->submitButton(array('Login', 'class' => 'btn btn-primary')); ?>
                </div>
            </fieldset>
        </div>

        <div class="col-lg-8 col-md-6">

            <div class="page-header">
                <h2>Don't have an account yet?</h2>
            </div>
            <p>Create an account to take full advantage of our website</p>
            <div class="clearfix center">
                <?php echo $this->tag->linkTo(array('user/register', 'class' => 'btn btn-primary btn-large btn-success'), 'Sign Up'); ?>
            </div>
        </div>
    </div>
</div>