<?php
/**
 * @copyright   2006 - 2015 Magnxpyr Network
 * @license     New BSD License; see LICENSE
 * @link        http://www.magnxpyr.com
 * @author      Stefan Chiriac <stefan@magnxpyr.com>
 * @var \Core\Forms\LoginForm $form
 * @var \Phalcon\Mvc\View\Engine $this
 */

echo $this->getContent();
?>
<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="col-sm-9 col-md-9">
            <?php echo $this->tag->form(array('user/login')); ?>
            <?php echo $form->render('csrf'); ?>

            <fieldset>
                <div class="form-group">
                    <?php echo $form->label('username', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="username-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <?php echo $form->render('username', array('class' => 'form-control', 'aria-describedby' => "username-addon")); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo $form->label('password', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="password-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <?php echo $form->render('password', array('class' => 'form-control', 'aria-describedby' => "password-addon")); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <?php echo $form->render('remember') . ' ' . $form->label('remember'); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <?php echo $this->tag->linkTo('user/forgotPassword', 'Forgot my password'); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo $form->render('Login'); ?>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="col-sm-6 col-md-6">
        <div class="col-sm-9 col-md-9">
            <div class="page-header">
                <h2>Don't have an account yet?</h2>
            </div>
            <p>Create an account to take full advantage of our website

                <?php echo $this->tag->linkTo(array('user/register', 'Sign Up', 'class' => 'btn btn-success')); ?>
            </p>
        </div>
    </div>
</div>