<?php
/**
 * @copyright   2006 - 2015 Magnxpyr Network
 * @license     New BSD License; see LICENSE
 * @link        http://www.magnxpyr.com
 * @author      Stefan Chiriac <stefan@magnxpyr.com>
 * @var \Core\Forms\RegisterForm $form
 */

echo $this->getContent();
?>
                    <!--Remove the Title page-->

<div class="register-page">
    <div class="register-box">
        <div class="register-box-body">
            <p class="register-box-msg">Register a new membership</p>
            <?php echo $this->tag->form(array('user/register')); ?>
            <fieldset>
                <div class="form-group">
                    <?php echo $form->label('username', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="username-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <?php echo $form->render('username', array('class' => 'form-control', 'aria-describedby' => "username-addon")); ?>
                    </div>
                </div>

                <div class="form-group">

                    <?php echo $form->label('email', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="email-addon">@</span>
                        <?php echo $form->render('email', array('class' => 'form-control', 'aria-describedby' => "email-addon")); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo $form->label('password', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="password-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <?php echo $form->render('password', array('class' => 'form-control', 'aria-describedby' => "password-addon")); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo $form->label('repeatPassword', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="password-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <?php echo $form->render('repeatPassword', array('class' => 'form-control', 'aria-describedby' => "password-addon")); ?>
                    </div>
                </div>

                        <!--Make a terms and privacy policy-->

                    <label>
                        <p class="help-block">By signing up, you accept the <a href="#">terms</a> of use and <a href="#">privacy policy</a>.</p>
                    </label>

                        <!--change the button of "Register" to "Sign Up"-->

                    <?php echo $form->render('Register'); ?>

                <div class="social-auth-links text-center">
                    <p>or</p>
                    <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using Facebook</a>
                    <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign up using Google+</a>
                </div>

                        <!--link this to login-->

                <a href="login.phtml" class="text-center">I already have a membership</a>

            </fieldset>
        </div>
    </div>
</div>