<?php
/**
 * @copyright   2006 - 2015 Magnxpyr Network
 * @license     New BSD License; see LICENSE
 * @link        http://www.magnxpyr.com
 * @author      Stefan Chiriac <stefan@magnxpyr.com>
 * @var \Core\Forms\RegisterForm $form
 */

echo $this->getContent();
?>
<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="col-sm-9 col-md-9">
            <?php echo $this->tag->form(array('user/register')); ?>

            <fieldset>
                <div class="form-group">
                    <?php echo $form->label('username', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="username-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <?php echo $form->render('username', array('class' => 'form-control', 'aria-describedby' => "username-addon")); ?>
                    </div>
                </div>

                <div class="form-group">

                    <?php echo $form->label('email', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="email-addon">@</span>
                        <?php echo $form->render('email', array('class' => 'form-control', 'aria-describedby' => "email-addon")); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo $form->label('password', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="password-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <?php echo $form->render('password', array('class' => 'form-control', 'aria-describedby' => "password-addon")); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?php echo $form->label('repeatPassword', array('class' => 'control-label')); ?>
                    <div class="input-group">
                        <span class="input-group-addon" id="password-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <?php echo $form->render('repeatPassword', array('class' => 'form-control', 'aria-describedby' => "password-addon")); ?>
                    </div>
                </div>

                <div class="form-group">
                    <p class="help-block">By signing up, you accept the terms of use and privacy policy.</p>
                    <?php echo $form->render('Register'); ?>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="col-md-6 col-sm-6">
    </div>
</div>