<?php
/**
 * @copyright   2006 - 2015 Magnxpyr Network
 * @license     New BSD License; see LICENSE
 * @link        http://www.magnxpyr.com
 * @author      Stefan Chiriac <stefan@magnxpyr.com>
 * @var \Phalcon\Mvc\View\Engine $this
 * @var \Core\Forms\LoginForm $form
 * @var int $status
 */

echo $this->getContent();
echo $this->tag->form(['user/reset-password']); ?>
    <fieldset>
        <div class="form-group form-max-size">
            <div class="form-group">
                <?php echo $form->label('password', array('class' => 'control-label')); ?>
                <div class="input-group">
                    <span class="input-group-addon" id="password-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <?php echo $form->render('password', array('class' => 'form-control', 'aria-describedby' => "password-addon")); ?>
                </div>
            </div>

            <div class="form-group">
                <?php echo $form->label('repeatPassword', array('class' => 'control-label')); ?>
                <div class="input-group">
                    <span class="input-group-addon" id="password-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <?php echo $form->render('repeatPassword', array('class' => 'form-control', 'aria-describedby' => "password-addon")); ?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->render('Send'); ?>
        </div>
    </fieldset>
</form>