<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 */

?>
<div class="row">
    <div class="col-md-3 col-sm-4">
        <div class="list-group">
            <?php require_once __DIR__ . "/../menu.phtml"; ?>
        </div>
    </div>
    <div class="col-md-9 col-sm-8">
        <div class="default-view">
            <h1>Create Module</h1>

            <?php echo $this->getContent() ?>
            <div class="col-lg-8 col-md-10">
                <form method="post" autocomplete="off" action="<?php echo \Tools\Helper\Tools::generateUrl('index', 'create') ?>">
                    <fieldset>
                        <div class="control-group">
                            <div class="form-group">
                                <label class="control-label" for="name">Controller name</label>
                                <?php echo $this->tag->textField(array(
                                    'name',
                                    'class' => 'form-control',
                                    'required' => 'required'
                                )) ?>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="name">Directory</label>
                                <?php echo $this->tag->textField(array(
                                    'dir',
                                    'class' => 'form-control',
                                    'required' => 'required'
                                )) ?>
                            </div>
                            <div class="form-group">
                                <label class="help" data-original-title="" title="">
                                    <?php echo $this->tag->checkField(array("force", "value" => 1)) . ' Force' ?>
                                </label>

                            </div>
                            <div align="right">
                                <input type="submit" class="btn btn-primary" value="Generate"/>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
