<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a href="devtools" class="brand">Phalcon Web Tools</a>
			<div class="nav-collapse">
				<ul class="nav"><?php echo \Modules\DevTools\Controllers\Tools::getNavMenu($this->view->getControllerName()) ?></ul>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<div class="well">
				<ul class="nav nav-list">
					<?php \Modules\DevTools\Controllers\Tools::getMenu($this->view->getControllerName(), $this->view->getActionName()) ?>
				</ul>
			</div>
		</div>
		<div class="span10 well">
			<?php echo $this->getContent() ?>
		</div>
	</div>
</div>