<h2 style="font-size: 14px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">You're Almost There! Just Confirm Your Email</h2>
<p style="font-size: 13px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">You've successfully created a <?php echo $siteName ?> account. To activate it, please click below to verify your email address.
    <br /><br />
    <a style="background:#E86537;color:#fff;padding:10px" href="<?php echo $confirmUrl ?>">Confirm</a>
    <br /><br />
    Enjoy!
</p>
