<h2 style="font-size: 14px">Dear <?php echo $name ?>,</h2>
<p style="font-size: 13px;line-height:24px;">
    A request has been made to reset your <?php echo $siteName ?> Account password.<br />
    Please click the following link to complete the change request.
    <br /><br />
    <a style="background:#E86537;color:#fff;padding:10px" href="<?php echo $resetUrl ?>">Reset Password</a>
    <br /><br />
    If you didn't requested a password change, please ignore this email.
</p>
