<?php
/**
 * @var string $sidebar_collapse
 */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <?php echo $this->tag->getTitle(); ?>
    <?php echo $this->assets->outputCss('header-css'); ?>
    <?php echo $this->assets->outputCss('header-css-min'); ?>
    <?php echo $this->assets->outputJs('header-js-min'); ?>
    <?php echo $this->assets->outputJs('header-js'); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="CMS">
    <meta name="author" content="Magnxpyr Network">
</head>
<body class="skin-blue sidebar-mini fixed <?php echo $sidebar_collapse ?>">
<?php echo $this->getContent(); ?>
</body>
</html>