<style>
    .search-bar {
        margin-top: 9px;
    }
    @media (min-width: 768px) {
        .header-search {
            width: 230px;
            position: relative;
        }

        .header-search input {
            position: relative;
            width: 0;
            float: left;
            -webkit-transition: all 0.7s ease-in-out;
            -moz-transition: all 0.7s ease-in-out;
            -o-transition: all 0.7s ease-in-out;
            transition: all 0.7s ease-in-out;
            border-radius:0;
            padding: 2px 10px;
            background: transparent;
            border: 0;
            box-shadow: none;
        }

        .header-search:hover input, .header-search input:focus {
            width: 200px;
            margin-left: 0;
            color: #ffffff;
            font-weight: bold;
            background: rgba(51, 85, 118,.8);
        }

        .header-search input::placeholder {
            color: #ffffff;
            font-weight: normal;
        }

        .btn-srch {
            position: relative;
            border: 0;
            background: transparent;
            margin: 10px;
            color: #ffffff;
            line-height: 30px;
        }

        .search-submit {
            display: none;
        }
    }
    @media (max-width: 768px) {
        .btn-srch {
            display: none;
        }
        .search-submit {
            width: 19%;
            height: 34px;
            vertical-align: top;
            display: inline-block;
            background: rgba(255, 255, 255, .2);
            border: 0;
            color: #ffffff;
        }
        .header-search input {
            width: 80%;
            display: inline-block;
            color: #ffffff;
            font-weight: bold;
            background: rgba(255, 255, 255, .2);
            border: 0;
            box-shadow: none;
        }
        .header-search input::placeholder {
            color: #ffffff;
        }
    }
</style>