<?php
/**
 * @var \Phalcon\Mvc\View\Engine $this
 */

echo $this->getContent();
?>

<h1>Create $plural$</h1>

<div class="col-md-6 col-sm-6">
    <?php echo $this->tag->form("$plural$/create") ?>
        <?php echo $this->tag->linkTo(array("$plural$", "Back")) ?>
        <fieldset>
            $captureFields$
            <div class="form-group">
                <?php echo $this->tag->submitButton(array('Save', 'class' => 'btn btn-success')); ?>
            </div>
        </fieldset>
    </form>
</div>
