<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 */

use Tools\Helpers\Tools;
?>
<?php Phalcon\Web\CodeMirror::importResources(); ?>

<div class="row">
    <div class="col-md-3 col-sm-4">
        <div class="list-group">
            <?php echo Tools::getNavMenu($this->view->getControllerName()) ?>
        </div>
    </div>
    <div class="col-md-9 col-sm-8">
        <div class="default-view">
            <ul class="nav nav-tabs">
                <?php Tools::getMenu($this->view->getControllerName(), $this->view->getActionName()) ?>
            </ul>

            <h2>Editing Controller <?php echo $name; ?></h2>

            <?php echo $this->getContent() ?>

            <form method="post" action="<?php echo $this->url->get("controllers/save") ?>">

                <p>
                    <div align="right">
                        <input type="submit" class="btn btn-primary" value="Save"/>
                    </div>
                </p>

                <?php echo $this->tag->textArea(array('code', 'cols' => 50, 'rows' => 20)) ?>

                <?php echo $this->tag->hiddenField('name') ?>

            </form>

		</div>
	</div>
</div>