<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 */

use Tools\Helpers\Tools;
?>
<div class="row">
    <div class="col-md-3 col-sm-4">
        <div class="list-group">
            <?php echo Tools::getNavMenu($this->view->getControllerName()) ?>
        </div>
    </div>
    <div class="col-md-9 col-sm-8">
        <div class="default-view">
            <ul class="nav nav-tabs">
                <?php Tools::getMenu($this->view->getControllerName(), $this->getView()->getActionName()) ?>
            </ul>

            <h1>Create Controller</h1>

            <?php echo $this->getContent() ?>
            <div class="col-lg-8 col-md-10">
                <form method="post" autocomplete="off" action="<?php echo Tools::generateUrl('index', 'create') ?>">
                    <fieldset>
                        <div class="control-group">
                            <div class="form-group">
                                <label class="control-label" for="name">Module</label>
                                <?php echo Phalcon\Tag::select(array(
                                    'module',
                                    'class' => 'form-control',
                                    'required' => 'required'
                                ), Tools::listModules()) ?>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="name">Controller name</label>
                                <?php echo Phalcon\Tag::textField(array(
                                    'name',
                                    'class' => 'form-control',
                                    'required' => 'required'
                                )) ?>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="name">Directory</label>
                                <?php echo Phalcon\Tag::textField(array(
                                    'dir',
                                    'class' => 'form-control',
                                    'required' => 'required'
                                )) ?>
                            </div>
                            <div class="form-group">
                                <label class="help" data-original-title="" title="">
                                    <?php echo Phalcon\Tag::checkField(array("force", "value" => 1)) . ' Force' ?>
                                </label>

                            </div>
                            <div align="right">
                                <input type="submit" class="btn btn-primary" value="Generate"/>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
