<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var string $selectedModule
 * @var string $directoryPath
 */

use Tools\Helpers\Tools;
?>
<div class="row">
    <div class="col-md-3 col-sm-4">
        <div class="list-group">
            <?php echo Tools::getNavMenu($this->view->getControllerName()) ?>
        </div>
    </div>
    <div class="col-md-9 col-sm-8">
        <div class="default-view">
            <h1>Create Controller</h1>

            <?php echo $this->getContent() ?>
            <div class="col-lg-8 col-md-10">
                <form method="post" autocomplete="off" action="<?php echo Tools::generateUrl('controllers', 'create') ?>">
                    <fieldset>
                        <div class="control-group">
                            <div class="form-group">
                                <label class="control-label" for="name">Module</label>
                                <select id="module" name="module" class="form-control">
                                <?php echo Tools::listModuleOptions($selectedModule) ?>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="name" aria-describedby="helpController">Controller name</label>
                                <?php echo Phalcon\Tag::textField(array(
                                    'name',
                                    'class' => 'form-control',
                                    'required' => 'required'
                                )) ?>
                                <span id="helpController" class="help-block">ex: ExampleController</span>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="name" aria-describedby="helpDirectory">Directory</label>
                                <?php echo Phalcon\Tag::textField(array(
                                    'directory',
                                    'class' => 'form-control',
                                //    'value' => $directoryPath
                                )) ?>
                                <span id="helpDirectory" class="help-block">Leave empty for <?php echo Tools::getModulesDir(). 'ModuleName'. DIRECTORY_SEPARATOR . Tools::getControllersDir() ?></span>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="name" aria-describedby="helpNamespace">Namespace</label>
                                <?php echo Phalcon\Tag::textField(array(
                                    'namespace',
                                    'class' => 'form-control',
                                //    'value' => $selectedModule . Tools::getControllersDir()
                                )) ?>
                                <span id="helpNamespace" class="help-block">Leave empty for ModuleName\<?php echo Tools::getControllersDir() ?></span>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="name" aria-describedby="helpBaseClass">Base Class</label>
                                <?php echo Phalcon\Tag::textField(array(
                                    'baseClass',
                                    'class' => 'form-control'
                                )) ?>
                                <span id="helpBaseClass" class="help-block">Leave empty for \Phalcon\Mvc\Controller</span>
                            </div>
                            <div class="form-group">
                                <label class="help" data-original-title="" title="">
                                    <?php echo Phalcon\Tag::checkField(array("view", "value" => 1)) . ' Create View' ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label class="help" data-original-title="" title="">
                                    <?php echo Phalcon\Tag::checkField(array("force", "value" => 1)) . ' Force' ?>
                                </label>
                            </div>
                            <div align="right">
                                <input type="submit" class="btn btn-primary" value="Generate"/>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
