<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var \Tools\Controllers\ControllersController $controllersDir
 */

?>
<div class="row">
	<div class="col-md-3 col-sm-4">
		<div class="list-group">
			<?php require_once __DIR__ . "/../menu.phtml"; ?>
		</div>
	</div>
	<div class="col-md-9 col-sm-8">
		<div class="default-view">

			<h1>Edit Controllers</h1>

			<?php echo $this->getContent() ?>

			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<td><b>Name</b></td>
						<td><b>Size</b></td>
						<td></td>
					</tr>
				</thead>
				<tbody>
				<?php
					$iterator = new DirectoryIterator($controllersDir);
					foreach($iterator as $fileinfo){
						if(!$fileinfo->isDot()){
							echo '<tr>
								<td>', $fileinfo->getFileName(), '</td>
								<td>', $fileinfo->getSize(), '</td>
								<td><a href="', \Tools\Helper\Tools::generateUrl('controllers','edit', $fileinfo->getFileName()), '"
									class"="btn">Edit</a></td>
							</tr>';
						}
					}
				?>
				</tbody>
			</table>

		</div>
	</div>
</div>