<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Database overview</h3>
            <table class="table table-striped table-condensed">
                <tbody>
                <tr>
                    <td class="item">Database type</td>
                    <td id="ow-db-adapter"></td>
                </tr>
                <tr>
                    <td class="item">Hostname</td>
                    <td id="ow-db-hostname"></td>
                </tr>
                <tr>
                    <td class="item">Username</td>
                    <td id="ow-db-username"></td>
                </tr>
                <tr>
                    <td class="item">Password</td>
                    <td>****</td>
                </tr>
                <tr>
                    <td class="item">Database Name</td>
                    <td id="ow-db-name"></td>
                </tr>
                <tr>
                    <td class="item">Database Port</td>
                    <td id="ow-db-port"></td>
                </tr>
                <tr>
                    <td class="item">Database Prefix</td>
                    <td id="ow-db-prefix"></td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="2"></td>
                </tr>
                </tfoot>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Super user overview</h3>
            <table class="table table-striped table-condensed">
                <tbody>
                <tr>
                    <td class="item">Email</td>
                    <td id="ow-su-email"></td>
                </tr>
                <tr>
                    <td class="item">Username</td>
                    <td id="ow-su-username"></td>
                </tr>
                <tr>
                    <td class="item">Password</td>
                    <td>*****</td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="2"></td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>