<div class="container tabs-wrap" id="installer-tabs">
    <ul class="nav nav-tabs">
        <li class="active disabled" role="presentation">
            <a role="tab" aria-expanded="true" aria-controls="requirements-tab" href="#requirements-tab"
               data-toggle="tab">Requirements</a>
        </li>
        <li class="disabled">
            <a role="tab" aria-expanded="false" aria-controls="configuration-tab" href="#configuration-tab"
               data-toggle="tab">Configuration</a>
        </li>
        <li class="disabled">
            <a role="tab" aria-expanded="false" aria-controls="overview-tab" href="#overview-tab" data-toggle="tab">Overview</a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane active" id="requirements-tab" role="tabpanel">
            <?php $this->partial("index/requirements", ['required' => $required, 'recommended' => $recommended]); ?>
            <div class="btn-group pull-right">
                <a href="#" class="btn btn-primary" onclick="checkRequirements();" rel="next" title="Next">
                    <i class="fa fa-arrow-right"></i> Next</a>
            </div>
        </div>

        <div class="tab-pane" id="configuration-tab" role="tabpanel">
            <form id="configuration">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <h3>Database</h3>
                            <div class="content">
                                <div class="form-group row">
                                    <?= $form->label('db-adapter', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-db-adaptor">
                                        <?= $form->render('db-adapter', ['class' => 'form-control', 'required' => "required"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <?= $form->label('db-hostname', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-db-hostname">
                                        <?= $form->render('db-hostname', ['class' => 'form-control', 'required' => "required"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <?= $form->label('db-username', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-db-username">
                                        <?= $form->render('db-username', ['class' => 'form-control', 'required' => "required"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <?= $form->label('db-password', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-db-password">
                                        <?= $form->render('db-password', ['class' => 'form-control', 'required' => "required"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <?= $form->label('db-name', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-db-name">
                                        <?= $form->render('db-name', ['class' => 'form-control', 'required' => "required"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <?= $form->label('db-port', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-db-name">
                                        <?= $form->render('db-port', ['class' => 'form-control', 'required' => "required"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <?= $form->label('db-prefix', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-db-prefix">
                                        <?= $form->render('db-prefix', ['class' => 'form-control']) ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <h3>Super User Account Details</h3>
                            <div class="content">
                                <div class="form-group row">
                                    <?= $form->label('su-email', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-su-email">
                                        <?= $form->render('su-email', ['class' => 'form-control', 'required' => "required"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <?= $form->label('su-username', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-su-username">
                                        <?= $form->render('su-username', ['class' => 'form-control', 'required' => "required"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <?= $form->label('su-password', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-su-password">
                                        <?= $form->render('su-password', ['class' => 'form-control', 'required' => "required"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <?= $form->label('su-password-repeat', ['class' => 'control-label col-sm-4']) ?>
                                    <div class="col-sm-8" id="wrapper-su-password">
                                        <?= $form->render('su-password-repeat', ['class' => 'form-control', 'required' => "required"]) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </form>
        </div>

        <div class="btn-group pull-right">
            <a class="btn" href="#" rel="prev" title="Previous">
                <i class="fa fa-arrow-left"></i> Previous</a>
            <a class="btn btn-primary" href="#" onclick="checkConfiguration()" rel="next" title="Next">
                <i class="fa fa-arrow-right"></i> Next</a>
        </div>
    </div>

    <div class="tab-pane" id="overview-tab" role="tabpanel">
        <?php $this->partial("index/overview", ['required' => $required, 'recommended' => $recommended]); ?>
        <?php $this->partial("index/requirements", ['required' => $required, 'recommended' => $recommended]); ?>
        <a class="btn" href="#" rel="prev" title="Previous">
            <i class="fa fa-arrow-left"></i> Previous</a>
        <a class="btn btn-primary" href="#" onclick="cmsInstall()" rel="next" title="Next">
            <i class="fa fa-arrow-right"></i> Install</a>
    </div>
</div>

<?php
function isRequired($value) {
    if ($value) {
        echo '<span class="label label-success">Yes</span>';
    } else {
        echo '<span class="label label-danger">No</span>';
    }
}

function isRecommended($value, $reverse = false) {
    if ($value) {
        echo '<span class="label label-' . ($reverse ? 'danger' : 'success') . '">On</span>';
    } else {
        echo '<span class="label label-' . ($reverse ? 'success' : 'danger') . '">Off</span>';
    }
}
?>