<?php
/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var string $version
 * @var array $tables
 */

use Module\Tools\Helpers\Tools;

echo $this->getContent();
?>
<div class="box box-default">
    <div class="box-header">
        <ul class="nav nav-tabs">
            <?php echo Tools::getMenu($this->view->getControllerName(), $this->view->getActionName()) ?>
        </ul>
    </div>
    <div class="box-body">
        <form method="post" autocomplete="off"
              action="<?php echo Tools::generateUrl($this->view->getControllerName(), 'generate') ?>">
            <div class="form-group">
                <label class="control-label" for="packageType">Package Type</label>
                <?= Phalcon\Tag::select(["packageType", "class" => "form-control", "onchange" => "changePackage(this)"], \Engine\Package\PackageType::getConstants()) ?>
            </div>
            <div class="form-group">
                <?php echo Tools::renderPackageInput($selectedModule, MODULES_PATH) ?>
            </div>
            <div class="form-group">
                <label class="control-label" for="schema">Table name</label>
                <input list="table-name" name="table-name" class="form-control">
                <datalist id="table-name">
                    <?php foreach ($tables as $table) {
                        echo "<option value='$table'>";
                    } ?>
                </datalist>
            </div>
            <div align="right">
                <input type="submit" class="btn btn-primary" value="Generate"/>
            </div>
        </form>
    </div>
</div>


<?php $this->addViewJs("admin-migrations/index-scripts") ?>
