<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var string $version
 * @todo list versions and run individually
 */

use Module\Tools\Helpers\Tools;

echo $this->getContent();
?>
<div class="box box-default">
    <div class="box-header ">
        <ul class="nav nav-tabs">
            <?php echo Tools::getMenu($this->view->getControllerName(), $this->view->getActionName()) ?>
        </ul>
    </div>
    <div class="box-body">
        <form method="post" autocomplete="off"
              action="<?php echo Tools::generateUrl($this->view->getControllerName(), 'run') ?>">
            <div class="form-group">
                <label class="control-label" for="packageType">Package Type</label>
                <?= Phalcon\Tag::select(["packageType", "class" => "form-control", "onchange" => "changePackage(this)"], \Engine\Package\PackageType::getConstants()) ?>
            </div>
            <div class="form-group">
                <?php echo Tools::renderPackageInput($selectedModule, MODULES_PATH) ?>
            </div>
            <table class="table table-striped table-bordered table-condensed">
                <tr>
                    <td colspan="2">
                        <div align="right">
                            <input type="submit" class="btn btn-primary" value="Run"/>
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>

<?php $this->addViewJs("admin-migrations/index-scripts") ?>